# Generated by Django 5.0.2 on 2024-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('national_number', models.CharField(max_length=20)),
                ('insurance_number', models.CharField(max_length=20)),
                ('admission_number', models.CharField(max_length=20)),
                ('social_status', models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=20)),
                ('religion', models.CharField(choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحي'), ('Other than that', 'غير ذلك')], max_length=20)),
                ('profession', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city_village', models.CharField(max_length=255)),
                ('governorate', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(max_length=255)),
                ('emergency_contact_address', models.CharField(max_length=255)),
                ('emergency_contact_phone_number', models.CharField(max_length=20)),
                ('insurance_provider_contact_name', models.CharField(max_length=255)),
                ('insurance_provider_relationship', models.CharField(max_length=255)),
                ('insurance_provider_address', models.CharField(max_length=255)),
                ('insurance_provider_phone_number', models.CharField(max_length=20)),
                ('admitted_by', models.CharField(choices=[('reception', 'استقبال'), ('clinic', 'عيادة'), ('other', 'أخرى')], max_length=20)),
                ('accident_location', models.CharField(choices=[('home', 'المنزل'), ('work', 'العمل'), ('road', 'الطريق'), ('other', 'أخرى')], max_length=20)),
                ('police_report', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], max_length=20)),
                ('previous_admission', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], max_length=20)),
                ('treating_physician', models.CharField(max_length=255)),
                ('admission_department', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('room_grade', models.CharField(max_length=255)),
                ('initial_diagnosis', models.TextField()),
                ('admission_date', models.DateField()),
                ('admission_time', models.TimeField()),
                ('discharge_date', models.DateField()),
                ('discharge_time', models.TimeField()),
                ('length_of_stay', models.IntegerField()),
                ('final_diagnosis', models.TextField()),
                ('associated_diagnosis', models.TextField()),
                ('service_type', models.CharField(choices=[('free', 'مجاني'), ('economic', 'اقتصادي'), ('insurance', 'تأمين'), ('government', 'نفقة دولة')], max_length=20)),
                ('operation_procedures', models.TextField()),
                ('autopsy', models.CharField(choices=[('yes', 'نعم'), ('No', 'لا')], max_length=3)),
                ('discharge_status', models.CharField(choices=[('recovery', 'شفاء'), ('improvement', 'تحسن'), ('no_improvement', 'لم تتحسن'), ('death', 'وفاة')], max_length=20)),
                ('discharge_destination', models.CharField(choices=[('clinic', 'عيادة'), ('other_hospital', 'مستشفى أخرى'), ('request', 'خروج حسب الطلب'), ('home', 'المنزل')], max_length=20)),
            ],
        ),
    ]
