# Generated by Django 4.2 on 2024-04-04 21:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_number', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_provider_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_provider_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_provider_address', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_provider_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('admitted_by', models.CharField(blank=True, choices=[('reception', 'استقبال'), ('clinic', 'عيادة'), ('other', 'أخرى')], max_length=20, null=True)),
                ('accident_location', models.CharField(blank=True, choices=[('home', 'المنزل'), ('work', 'العمل'), ('road', 'الطريق'), ('other', 'أخرى')], max_length=20, null=True)),
                ('police_report', models.CharField(blank=True, choices=[('Yes', 'نعم'), ('No', 'لا')], max_length=20, null=True)),
                ('previous_admission', models.CharField(blank=True, choices=[('Yes', 'نعم'), ('No', 'لا')], max_length=20, null=True)),
                ('treating_physician', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_department', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('room_grade', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_diagnosis', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_time', models.TimeField(blank=True, null=True)),
                ('time_of_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'National ID must be 14 digits')])),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=20, null=True)),
                ('social_status', models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=20, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحي'), ('Other than that', 'غير ذلك')], max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city_village', models.CharField(blank=True, max_length=255, null=True)),
                ('governorate', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateField()),
                ('discharge_time', models.TimeField()),
                ('length_of_stay', models.IntegerField(blank=True, null=True)),
                ('final_diagnosis', models.TextField()),
                ('associated_diagnosis', models.TextField()),
                ('service_type', models.CharField(blank=True, choices=[('free', 'مجاني'), ('economic', 'اقتصادي'), ('insurance', 'تأمين'), ('government', 'نفقة دولة')], max_length=20, null=True)),
                ('operation_procedures', models.TextField(blank=True, null=True)),
                ('autopsy', models.CharField(blank=True, choices=[('yes', 'نعم'), ('No', 'لا')], max_length=3, null=True)),
                ('discharge_status', models.CharField(blank=True, choices=[('recovery', 'شفاء'), ('improvement', 'تحسن'), ('no_improvement', 'لم تتحسن'), ('death', 'وفاة')], max_length=20, null=True)),
                ('discharge_destination', models.CharField(blank=True, choices=[('clinic', 'عيادة'), ('other_hospital', 'مستشفى أخرى'), ('request', 'خروج حسب الطلب'), ('home', 'المنزل')], max_length=20, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='admission.admission')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admission.patient'),
        ),
    ]
