# Generated by Django 4.2 on 2024-03-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admission.patient')),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_time', models.TimeField(blank=True, null=True)),
                ('length_of_stay', models.IntegerField(blank=True, null=True)),
                ('final_diagnosis', models.TextField(blank=True, null=True)),
                ('associated_diagnosis', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('free', 'مجاني'), ('economic', 'اقتصادي'), ('insurance', 'تأمين'), ('government', 'نفقة دولة')], max_length=20, null=True)),
                ('operation_procedures', models.TextField(blank=True, null=True)),
                ('autopsy', models.CharField(blank=True, choices=[('yes', 'نعم'), ('No', 'لا')], max_length=3, null=True)),
                ('discharge_status', models.CharField(blank=True, choices=[('recovery', 'شفاء'), ('improvement', 'تحسن'), ('no_improvement', 'لم تتحسن'), ('death', 'وفاة')], max_length=20, null=True)),
                ('discharge_destination', models.CharField(blank=True, choices=[('clinic', 'عيادة'), ('other_hospital', 'مستشفى أخرى'), ('request', 'خروج حسب الطلب'), ('home', 'المنزل')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='associated_diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='autopsy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_destination',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='final_diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='length_of_stay',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operation_procedures',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='service_type',
        ),
    ]
