# Generated by Django 4.2 on 2024-04-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_discharge_associated_diagnosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discharge',
            old_name='admission',
            new_name='admission_number',
        ),
    ]
