# Generated by Django 4.2 on 2024-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_discharge_remove_patient_associated_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='associated_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='autopsy',
            field=models.CharField(blank=True, choices=[('yes', 'نعم'), ('No', 'لا')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_destination',
            field=models.CharField(blank=True, choices=[('clinic', 'عيادة'), ('other_hospital', 'مستشفى أخرى'), ('request', 'خروج حسب الطلب'), ('home', 'المنزل')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_status',
            field=models.CharField(blank=True, choices=[('recovery', 'شفاء'), ('improvement', 'تحسن'), ('no_improvement', 'لم تتحسن'), ('death', 'وفاة')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='final_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='length_of_stay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='operation_procedures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='service_type',
            field=models.CharField(blank=True, choices=[('free', 'مجاني'), ('economic', 'اقتصادي'), ('insurance', 'تأمين'), ('government', 'نفقة دولة')], max_length=20, null=True),
        ),
    ]
