# Generated by Django 4.2 on 2024-04-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_rename_admission_discharge_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='discharge_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
